name: deploy-helloworld
run-name: ${{ github.actor }} is saying hello
on: [push]
jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
    
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.1'
            extensions: none
            
      - name: Checkout code
        run: git clone https://github.com/javierwilson/helloworld.git
        
      - name: Check syntax
        run: php -l helloworld/src/index.php

      - name: creates ssh key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.HELLOWORLD_SSH_KEY }}" > ~/.ssh/helloworldkey
          chmod 600 ~/.ssh/helloworldkey
          
      - name: run remote update script
        run: ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/helloworldkey ${{ vars.SSH_DEPLOY_USER }}@${{ vars.SSH_DEPLOY_HOST }} /usr/local/bin/updatecode.sh
