name: deploy-helloworld
run-name: ${{ github.actor }} is saying hello
on: [push]
jobs:
  deploy-code:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh
          echo "${{ secrets.DOKKU_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=accept-new deploy@44.230.193.216 /usr/local/bin/updatecode.sh
